//
//  Embedding.swift
//  scAIper
//
//  Created by Dominik Hommer on 29.03.25.
//

import Foundation

/// A model representing an embedding vector associated with a unique identifier.
struct Embedding: Identifiable, Codable {
    
    /// A unique identifier for the embedding (used for list rendering or tracking).
    let id: UUID
    
    /// The actual embedding vector, usually generated by an LLM or other ML model.
    let vector: [Double]

    /// Initializes a new embedding with an optional UUID and a required vector.
    /// - Parameters:
    ///   - id: Optional UUID. Defaults to a new UUID if not provided.
    ///   - vector: The embedding vector as an array of Doubles.
    init(id: UUID = UUID(), vector: [Double]) {
        self.id = id
        self.vector = vector
    }
}

